"""
Shared MACRO_PLACER_* environment presets for ``backtest`` / ``evaluate``.

``--fast`` / ``--smoke`` apply condensed surrogate + oracle **budgets** for quicker wall-clock.
``--comp`` / ``--full`` set ``MACRO_PLACER_PROFILE`` and competition-quality budgets.

Phases keep the same ordering (multi-mode SA → oracle gates → refine passes); step counts and
SA length shrink on fast/smoke — proxy is not comparable to full-budget competition runs.
"""

from __future__ import annotations

import os
from typing import Dict

# Condensed surrogate/oracle budgets (same keys as legacy backtest ``_FAST_BACKTEST_ENV``).
FAST_MACRO_PLACER_ENV: Dict[str, str] = {
    "MACRO_PLACER_PROFILE": "fast",
    "MACRO_PLACER_TIME_SCALE": "0.04",
    "MACRO_PLACER_ITER_FLOOR": "160",
    "MACRO_PLACER_ITER_CAP": "300",
    "MACRO_PLACER_MODES": "3",
    "MACRO_PLACER_TOPK": "2",
    "MACRO_PLACER_CONGEST_BOOST": "0",
    "MACRO_PLACER_TORCH_REFINE": "0",
    "MACRO_PLACER_POLISH": "0",
    "MACRO_PLACER_ROUTE_BAL": "0.006",
    "MACRO_PLACER_ROUTE_PRESSURE_W": "0.0018",
    "MACRO_PLACER_AXIS_GREED": "26",
    "MACRO_PLACER_AXIS_GREED_PASS2": "22",
    "MACRO_PLACER_AXIS_PASS2_ENABLE": "1",
    "MACRO_PLACER_AXIS_GREED_PASS3": "18",
    "MACRO_PLACER_AXIS_PASS3_SCALE": "0.34",
    "MACRO_PLACER_AXIS_PASS3_ENABLE": "1",
    "MACRO_PLACER_AXIS_DELTA": "0.00935",
    "MACRO_PLACER_HOT_ESC_STEPS": "16",
    "MACRO_PLACER_HOT_ESC_GUARD": "0.71",
    "MACRO_PLACER_MULTIPOLE_STEPS": "16",
    "MACRO_PLACER_MULTIPOLE_GUARD": "0.695",
    "MACRO_PLACER_POLE_LS_ROUNDS": "10",
    "MACRO_PLACER_PAIR_POLE_STEPS": "10",
    "MACRO_PLACER_POST_LEGAL": "4",
    "MACRO_PLACER_REPEL_ROUNDS": "3",
    "MACRO_PLACER_COOL_BIN_HOT_BIAS": "0.82",
    "MACRO_PLACER_COOL_BIN_K": "20",
    "MACRO_PLACER_COOL_BIN_PATIENCE": "4",
    "MACRO_PLACER_COOL_BIN_STEPS": "18",
    "MACRO_PLACER_COOL_BIN_TRIALS": "6",
    "MACRO_PLACER_SWAP_PATIENCE": "3",
    "MACRO_PLACER_SWAP_STEPS": "14",
    "MACRO_PLACER_INCR_SCALE": "0.52",
    "MACRO_PLACER_PC_STEPS_CAP": "58",
}

SMOKE_MACRO_PLACER_ENV: Dict[str, str] = {
    **FAST_MACRO_PLACER_ENV,
    "MACRO_PLACER_TIME_SCALE": "0.03",
    "MACRO_PLACER_ITER_FLOOR": "90",
    "MACRO_PLACER_ITER_CAP": "110",
    "MACRO_PLACER_MODES": "1",
    "MACRO_PLACER_TOPK": "1",
    "MACRO_PLACER_ADAPT_MODES": "0",
    "MACRO_PLACER_FD_ITERS": "6",
    "MACRO_PLACER_AXIS_GREED": "0",
    "MACRO_PLACER_AXIS_GREED_PASS2": "0",
    "MACRO_PLACER_AXIS_GREED_PASS3": "0",
    "MACRO_PLACER_AXIS_PASS3_ENABLE": "0",
    "MACRO_PLACER_NET_HOT_BLEND": "0",
    "MACRO_PLACER_NET_HOT_HOTESC_BLEND": "0",
    "MACRO_PLACER_INCR_MACRO_BIAS": "0",
    "MACRO_PLACER_AXIS_NET_HOT_REFRESH_EVERY": "0",
    "MACRO_PLACER_LEGAL_CONG_ORDER": "0",
    "MACRO_PLACER_HOT_ESC_STEPS": "0",
    "MACRO_PLACER_INCREMACRO_ENABLE": "0",
    "MACRO_PLACER_MULTIPOLE_STEPS": "0",
    "MACRO_PLACER_MULTIPOLE_ENABLE": "0",
    "MACRO_PLACER_POLE_LS_ROUNDS": "0",
    "MACRO_PLACER_POLE_LS_ENABLE": "0",
    "MACRO_PLACER_PAIR_POLE_STEPS": "0",
    "MACRO_PLACER_PAIR_POLE_ENABLE": "0",
    "MACRO_PLACER_INCR_SCALE": "0.32",
    "MACRO_PLACER_PC_STEPS_CAP": "22",
    "MACRO_PLACER_REPEL_ROUNDS": "0",
    "MACRO_PLACER_POST_LEGAL": "1",
}

# Competition submission (~1h/benchmark default budget).
COMP_MACRO_PLACER_ENV: Dict[str, str] = {
    "MACRO_PLACER_PROFILE": "comp",
    "MACRO_PLACER_BUDGET_SECS": "3600",
    "MACRO_PLACER_TIME_SCALE": "1.0",
    "MACRO_PLACER_ITER_FLOOR": "1200",
    "MACRO_PLACER_ITER_CAP": "60000",
    "MACRO_PLACER_MODES": "5",
    "MACRO_PLACER_TOPK": "3",
    "MACRO_PLACER_ROUTE_BAL": "0.006",
    "MACRO_PLACER_ROUTE_PRESSURE_W": "0.0018",
    "MACRO_PLACER_CONGEST_BOOST": "0",
    "MACRO_PLACER_CONGEST_ROUTE_MULT": "1.35",
    "MACRO_PLACER_EPLACE_ITERS": "200",
    "MACRO_PLACER_EPLACE_LAMBDA_START": "0.001",
    "MACRO_PLACER_EPLACE_LAMBDA_GROWTH": "1.08",
    "MACRO_PLACER_ANALYTICAL_ITERS": "320",
    "MACRO_PLACER_LEDGER_SURR": "1",
    "MACRO_PLACER_LEDGER_SURR_MIN_ROWS": "50",
    "MACRO_PLACER_ORIENT_STEPS": "48",
    "MACRO_PLACER_POLISH": "1",
    "MACRO_PLACER_EDGE_ESC_STEPS": "24",
    "MACRO_PLACER_PC_STEPS_CAP": "120",
    "MACRO_PLACER_WL_FINAL_STEPS": "80",
    "MACRO_PLACER_AXIS_GREED": "48",
    "MACRO_PLACER_AXIS_GREED_PASS2": "40",
    "MACRO_PLACER_AXIS_GREED_PASS3": "32",
    "MACRO_PLACER_HOT_ESC_STEPS": "28",
    "MACRO_PLACER_MULTIPOLE_STEPS": "24",
    "MACRO_PLACER_POLE_LS_ROUNDS": "14",
    "MACRO_PLACER_PAIR_POLE_STEPS": "14",
}

# Local validation: comp surrogate tuning + oracle phases, ≤15 min/bench on ibm01-class designs.
VALIDATE_MACRO_PLACER_ENV: Dict[str, str] = {
    "MACRO_PLACER_PROFILE": "comp",
    "MACRO_PLACER_LEDGER_SURR": "0",
    "MACRO_PLACER_BUDGET_SECS": "720",
    "MACRO_PLACER_TIME_SCALE": "0.35",
    "MACRO_PLACER_ITER_FLOOR": "800",
    "MACRO_PLACER_ITER_CAP": "12000",
    "MACRO_PLACER_MODES": "4",
    "MACRO_PLACER_TOPK": "2",
    "MACRO_PLACER_ROUTE_BAL": "0.006",
    "MACRO_PLACER_ROUTE_PRESSURE_W": "0.0018",
    "MACRO_PLACER_CONGEST_BOOST": "0",
    "MACRO_PLACER_CONGEST_ROUTE_MULT": "1.5",
    "MACRO_PLACER_COOLBIN_NET_HOT": "1",
    "MACRO_PLACER_NET_HOT_COOLBIN_BLEND": "0.5",
    "MACRO_PLACER_PROXY_SA": "0",
    "MACRO_PLACER_GWTW_WORKERS": "8",
    "MACRO_PLACER_GWTW_SYNC_FREQ": "0.1",
    "MACRO_PLACER_GWTW_SYNC_FRAC": "0.1",
    "MACRO_PLACER_GWTW_TOP_K": "2",
    "MACRO_PLACER_ORACLE_SEC": "0.1",
    "MACRO_PLACER_PROXY_SA_ITERS_PER_SYNC": "36",
    "MACRO_PLACER_EPLACE_ITERS": "96",
    "MACRO_PLACER_ANALYTICAL_ITERS": "80",
    "MACRO_PLACER_LEDGER_SURR_MIN_ROWS": "50",
    "MACRO_PLACER_ORIENT_STEPS": "0",
    "MACRO_PLACER_POLISH": "0",
    "MACRO_PLACER_EDGE_ESC_STEPS": "12",
    "MACRO_PLACER_PC_STEPS_CAP": "48",
    "MACRO_PLACER_WL_FINAL_STEPS": "40",
    "MACRO_PLACER_AXIS_GREED": "32",
    "MACRO_PLACER_AXIS_GREED_PASS2": "24",
    "MACRO_PLACER_HOT_ESC_STEPS": "12",
    "MACRO_PLACER_MULTIPOLE_STEPS": "12",
    "MACRO_PLACER_POLE_LS_ROUNDS": "8",
    "MACRO_PLACER_PAIR_POLE_STEPS": "8",
    "MACRO_PLACER_TORCH_REFINE": "0",
}

FULL_MACRO_PLACER_ENV: Dict[str, str] = {
    **COMP_MACRO_PLACER_ENV,
    "MACRO_PLACER_PROFILE": "full",
    "MACRO_PLACER_BUDGET_SECS": "7200",
    "MACRO_PLACER_ITER_CAP": "120000",
    "MACRO_PLACER_EPLACE_ITERS": "400",
    "MACRO_PLACER_ANALYTICAL_ITERS": "480",
    "MACRO_PLACER_PC_STEPS_CAP": "200",
    "MACRO_PLACER_WL_FINAL_STEPS": "120",
    "MACRO_PLACER_ORIENT_STEPS": "64",
}


def apply_preset_env(preset: Dict[str, str]) -> None:
    """Set ``MACRO_PLACER_*`` keys not already exported (explicit env overrides preset)."""
    for key, val in preset.items():
        if key not in os.environ:
            os.environ[key] = val
